     "AAA", "AAA"
     "AAA", "aAA"
     "aAA", "AAA"
     "AAA", "aAA"
     "AAA", "AAAA"
     "AAA", "AAA "
     "CAA", "AAA"
     "AAA", "CAA"
     "000", "333"
     "000", "AAA"
     "???", "AAA"
